import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ryan Malawa Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">RyanM</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Ryan Malawa
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Backend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            &quot;Results-driven backend developer focused on delivering reliable and functional code solutions. With a proactive and problem-solving mindset, I am dedicated to meeting project goals and ensuring the successful implementation of your requirements. Let&apos;s collaborate and create something exceptional.&quot;
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="flex justify-center items-center h-screen">
  <div className="bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
    <Image src={deved} layout="fill" alt='manwaving'objectFit="cover" />
  </div>
</div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Areas of Focus</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            As a passionate and eager-to-learn backend developer, I have been actively involved in various projects, collaborating with professionals from different backgrounds. I have gained valuable experience working with 
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              to create digital products that cater to diverse business and consumer needs.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including backend development, database management, and system architecture. As a dedicated learner and enthusiast, I am eager to collaborate on projects that allow me to leverage my skills in these areas.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="design"/>
              <h3 className="text-lg font-bold pt-8 pb-2  ">
                Backend Development
              </h3>
              <p className="py-2">
              Crafting elegant and functional designs tailored to your needs is my specialty as a backend developer.
              </p>
              <h4 className="py-4 font-bold text-teal-600">Backend Tech Stack I Use</h4>
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">Express JS</p>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="code"/>
              <h3 className="text-lg font-bold pt-8 pb-2 ">
              Powering Your Dream Project with Proficient Database Management
              </h3>
              <p className="py-2">
                 Have an exciting website idea in mind? Let&apos;s transform it into a reality. 
              </p>
              <h4 className="py-4 font-bold text-teal-600">Database Expertise</h4>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">Supabase</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="thumb" />
              <h3 className="text-lg font-bold pt-8 pb-2 ">Frontend Expertise</h3>
              <p className="py-2">
              Ready to transform your ideas into an exceptional frontend experience? I specialize in building captivating and functional frontends that leave a lasting impression.
              </p>
              <h4 className="py-4 font-bold text-teal-600">Tech Stack</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Throughout my journey as a versatile backend developer, I have successfully completed an array of projects spanning different industries.
              
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Some of the projects I have worked on include the following:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <div
                  className="rounded-lg border border-gray-300"
                  style={{
                    width: "100%",
                    height: "100%",
                    aspectRatio: "16/9",
                  }}
              >
              <div className="flex flex-col justify-end h-full p-4 mt-4">
                <p className="text-lg font-bold">GeminiUser:</p>
                <p className="text-md py-2">A cutting-edge project leveraging the power of NodeJs, Express and Supabase to revolutionize user authentication systems.</p>
                <a
                  href="https://github.com/mryan-3/GeminiUser.git"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center mt-2 text-teal-500"
                >
                  Project Code
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    className="w-4 h-4 ml-1"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 5l7 7-7 7"
                    />
                  </svg>
                </a>
              </div>
            </div>
          </div>
            <div className="basis-1/3 flex-1">
              <div
                className="rounded-lg border border-gray-300"
                style={{
                  width: "100%",
                  height: "100%",
                  aspectRatio: "16/9",
                }}
              >
              <div className="flex flex-col justify-end h-full p-4 mt-4">
                <p className="text-lg font-bold">TaskOptima</p>
                <p className="text-md py-2"> A powerful backend built with Node.js, Express, and Supabase, designed to streamline task management while seamlessly integrating with OpenAI for intelligent insights.</p>
                <a
                  href="https://github.com/mryan-3/TaskOptima.git"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center mt-2 text-teal-500"
                >
                  Project Code
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    className="w-4 h-4 ml-1"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 5l7 7-7 7"
                    />
                  </svg>
                </a>
              </div>
            </div>
            </div>
            <div className="basis-1/3 flex-1">
            <div
              className="rounded-lg border border-gray-300"
              style={{
                width: "100%",
                height: "100%",
                aspectRatio: "16/9",
              }}
            >
            <div className="flex flex-col justify-end h-full p-4 mt-4 ">
              <p className="text-lg font-bold">AI Hub</p>
              <p className="text-md py-2"> &quot;A dynamic project combining Node.js, Express, and the Africa&apos;s Talking API to enable SMS communication from your application with just a prompt, inspired by the chat-based GPT AI model.&quot;</p>
              <a
                href="https://github.com/mryan-3/smsRoute.git"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center mt-2 text-teal-500"
              >
                Project Code
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  className="w-4 h-4 ml-1"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 5l7 7-7 7"
                  />
                </svg>
              </a>
            </div>
          </div>
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}
